groups:
- name: "cpu_temp"
  rules:
  - alert: HighCPUTemperature
    expr: max by (instance)(temperatureProbeReading{temperatureProbeLocationName=~"CPU.*"})/10 > 40
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU temperature detected"
      description: "CPU temperature is above 50°C on {{ $labels.instance }}"

