route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'postbin'
receivers:
  - name: 'postbin'
    webhook_configs:
      - url: 'https://www.postb.in/b/1741453857996-5340727781876'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
