route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'postbin'
receivers:
  - name: 'postbin'
    webhook_configs:
      - url: '{{ .Env.ALERTMANAGER_POST_URL }}'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
