volumes:
  snmp_config:
  prom_data:
  loki_data:
  grafana_data:

services:
  snmp-config-generator:
    image: ghcr.io/ocp-on-nerc/snmp-config-generator:latest
    volumes:
    - './snmp/generator.yml:/src/generator.yml'
    - snmp_config:/out
    entrypoint:
    - sh
    - -c
    - |
      generator generate -m /mibs -g /src/generator.yml -o /out/snmp.yml

  snmp-exporter:
    image: quay.io/prometheus/snmp-exporter:latest
    volumes:
    - snmp_config:/config
    depends_on:
      snmp-config-generator:
        condition: service_completed_successfully
    command:
    - --config.file=/config/snmp.yml
    ports:
    - 9116:9116

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    volumes:
    - ./blackbox:/config
    command:
    - --config.file=/config/blackbox.yml
    - --log.level=WARN
    ports:
    - 9115:9115

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    volumes:
    - ./prometheus:/config
    - prom_data:/prometheus
    command:
    - --config.file=/config/prometheus.yml
    ports:
    - 9090:9090

  promtail:
    image: docker.io/grafana/promtail:latest
    volumes:
    - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command:
    - -config.file
    - /etc/promtail/promtail.yml

  syslog-ng:
    image: docker.io/balabit/syslog-ng:latest
    volumes:
    - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    ports:
    - 5140:5140/udp

  loki:
    image: docker.io/grafana/loki:latest
    volumes:
    - loki_data:/loki

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/etc/grafana/dashboards

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    volumes:
    - ./alertmanager:/config
    command:
    - --config.file=/config/alertmanager.yml
