apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus

      # This should be >= the scrape interval set in prometheus (otherwise
      # things like $__rate_interval won't work correctly).
      timeInterval: 60s
