{
 "title": "IDRAC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up,instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemModelName{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemServiceTag{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "amperageProbe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "amperageProbeReading{instance=~\"$instance\"}/10",
     "legendFormat": "{{amperageProbeLocationName}}"
    }
   ]
  },
  {
   "title": "temperatureProbe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperatureProbeReading{instance=~\"$instance\"}/10",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "coolingDevice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "coolingDeviceReading{instance=~\"$instance\"}/10",
     "legendFormat": "{{coolingDeviceLocationName}}"
    }
   ]
  },
  {
   "title": "powerUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(powerUsageCumulativeWattage{instance=\"$instance\"}[5m])",
     "legendFormat": "powerUsageCumulativeWattage"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{instance=\"$instance\",ifName=\"bond0\"}[5m])",
     "legendFormat": "{{ifName}} IN"
    },
    {
     "expr": "-rate(ifOutOctets{instance=\"$instance\",ifName=\"bond0\"}[5m])",
     "legendFormat": "{{ifName}} OUT"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance, temperatureProbeLocationName)(temperatureProbeReading{instance=\"$instance\", temperatureProbeLocationName=~\"CPU.*\"})/10",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=~\"10.2.11.112\"} |= ``"
    }
   ]
  }
 ]
}