{
 "title": "IDRAC Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "systemFQDN\n* on(instance) group_left(systemModelName) systemModelName\n* on(instance) group_left(systemBladeSlotNumber) systemBladeSlotNumber\n* on(instance) group_left(systemServiceTag) systemServiceTag\n* on(instance) group_left(systemBIOSVersionName) systemBIOSVersionName\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "powerUsageCumulativeWattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance)(rate(powerUsageCumulativeWattage[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (instance)(temperatureProbeReading{temperatureProbeLocationName=~\"CPU.*\"})/10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}